# Generated by Django 5.1 on 2024-10-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_images',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
