# Generated by Django 5.0 on 2024-10-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_teammember_task_budget_amount_task_task_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="budget_amount",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=10),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_duration",
            field=models.CharField(default="0", max_length=20),
        ),
    ]
