# Generated by Django 5.0.7 on 2024-10-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_task_budget_amount_alter_task_task_duration'),
        ('frontend', '0003_event'),
    ]

    operations = [
    ]
