# Generated by Django 5.0.7 on 2024-10-20 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_merge_20241020_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='role',
            field=models.CharField(default='Member', max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('manager', 'Team Manager'), ('developer', 'Developer'), ('qa', 'QA Engineer')], default='Developer', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='working_projects',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='experience',
            field=models.PositiveIntegerField(help_text='Years of experience'),
        ),
    ]
