# Generated by Django 5.0.7 on 2024-10-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_task_role_teammember_profile_image_teammember_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.IntegerField(),
        ),
    ]
