# Generated by Django 5.0.7 on 2024-10-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_task_task_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('Manager', 'Team Manager'), ('Developer', 'Developer'), ('Qa', 'QA Engineer')], default='Developer', max_length=20),
        ),
    ]
